apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: awsmanaged-cluster
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta2
    kind: AWSManagedControlPlane
    name: awsmanaged-cluster-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
    kind: AWSManagedCluster
    name: awsmanaged-cluster
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSManagedCluster
metadata:
  name: awsmanaged-cluster
  namespace: default
spec: {}
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: AWSManagedControlPlane
metadata:
  name: awsmanaged-cluster-control-plane
  namespace: default
spec:
  region: us-west-2
  sshKeyName: shaunak-key-2
  version: v1.22.0
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: awsmanaged-cluster-pool-0
  namespace: default
spec:
  clusterName: awsmanaged-cluster
  replicas: 1
  template:
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: awsmanaged-cluster
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
        kind: AWSManagedMachinePool
        name: awsmanaged-cluster-pool-0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSManagedMachinePool
metadata:
  name: awsmanaged-cluster-pool-0
  namespace: default
spec: 
  scaling:
     minSize: 0
     maxSize: 5		
